# Generated by Django 6.0.6 on 2026-07-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating_score', models.FloatField(default=0.0)),
                ('rating_text', models.CharField(blank=True, max_length=50, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('new_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating_score', models.FloatField(default=0.0)),
                ('rating_text', models.CharField(blank=True, max_length=50, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('new_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SewaMobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departure', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='transportations/')),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departure', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='transportations/')),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating_score', models.FloatField(default=0.0)),
                ('rating_text', models.CharField(blank=True, max_length=50, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('new_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
